[Interface]
Address = 10.10.11.126/32
PrivateKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DNS = 8.8.8.8, 8.8.4.4
MTU = 1280

[Peer]
Endpoint = vpn.xxx.com:51820
PublicKey = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AllowedIPs = 0.0.0.0/0

# [Peer] TURN extensions
#@wgt:EnableTURN = true
#@wgt:UseUDP = false
#@wgt:IPPort = 11.22.33.44:56000
#@wgt:VKLink = https://vk.ru/call/join/xxxxxxxxxxxxxxxxxx
#@wgt:StreamNum = 4
#@wgt:LocalPort = 9000
#@wgt:TurnIP = 155.212.199.166      # (optional) Override TURN server IP
#@wgt:TurnPort = 19302              # (optional) Override TURN server port
#@wgt:NoDTLS = false                # (optional) Disable DTLS obfuscation (for direct WG server access)
